apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: dbatruh/hello-gitops
  newTag: a3dca8da327e615b5d7933ccdb31dd045b3c419b
